    - name: Build ATC_Thermometer
      env:
        TEL_PATH: /opt/Telink_825X_SDK
      run: |
        # Startet den Build direkt im Hauptverzeichnis mit dem nativen Linux-Support des makefiles
        make
        
        # Zeigt dir am Ende die fertigen Firmware-Dateien an
        cd $GITHUB_WORKSPACE
        ls -la bin/
